GET http://localhost:3001/api/houses

###
GET http://localhost:3001/api/houses/

###
POST http://localhost:3001/api/houses
Content-Type: application/json

{
    "houseName": "Domek Macieja",
    "rooms": [
        {
            "name": "Pokój Macieja",
            "size": 1
        },
        {
            "name": "Pokój Michała",
            "size": 2
        }
    ]
}

###
DELETE http://localhost:3001/api/houses/634332fa1f9f5ba4eb8b5383

###
PATCH http://localhost:3001/api/houses/6331f7cc3abf2bd1cbf7997c
Content-Type: application/json

{
    "houseName": "Paweł"
}