GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Anna",
    "surname": "Wanna",
    "nickname": "Bath",
    "age": 32,
    "gender": "m",
    "password": "123!Dupa",
    "withWho": "",
    "isAdmin": true,
}

###
DELETE http://localhost:3001/api/users/634318b7877459298db6f250

###
PATCH http://localhost:3001/api/users/6331f7cc3abf2bd1cbf7997c
Content-Type: application/json

{
    "name": "Paweł"
}