# Generated by Django 4.1.1 on 2022-09-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_roomates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='x-bedded Room', max_length=50),
        ),
    ]
